USE tdw;

-- Pulisce la tabella prima di caricare il routing
DELETE FROM service WHERE TRUE;

INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/', 'home.php', 'home', 'Home');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/sign-in', 'auth/access.php', 'signIn', 'Login');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/sign-up', 'auth/access.php', 'signUp', 'Registrazione');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/sign-out', 'auth/access.php', 'signOut', 'Logout');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/product/%', 'product.php', 'product', 'Product Page');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public',  '/products%', 'products.php', 'products', 'Product Search Page');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Admin', '/admin', 'admin/index.php', 'admin', 'Dashboard');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/categories', 'categories.php', 'categories', 'Categories Page');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/category/%', 'category.php', 'category', 'Category Page');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/brand/%', 'brand.php', 'brand', 'Brand Page');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/contact', 'contact.php', 'contact', 'Contacts Page');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Public', '/about', 'about.php', 'about', 'About Page');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Profilo', '/profile', 'user/profile.php', 'profile', 'Pagina Personale');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Carrello', '/cart', 'user/cart.php', 'cart', 'Pagina Carrello');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Carrello', '/cart/add', 'user/cart.php', 'add', 'Aggiungi prodotto al carrello');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Carrello', '/cart/clear', 'user/cart.php', 'clear', 'Pulisci carrello');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Carrello', '/cart/quantity', 'user/cart.php', 'editQuantity', 'Modifica quantità');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Carrello', '/cart/remove', 'user/cart.php', 'remove', 'Rimuovi prodotto');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Carrello', '/cart/coupon/apply', 'user/cart.php', 'applyCoupon', 'Applica Coupon');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Wishlist', '/wishlist', 'user/wishlist.php', 'wishlist', 'Wishlist');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Wishlist', '/wishlist/add', 'user/wishlist.php', 'add', 'Aggiungi prodotto alla Wishlist');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Wishlist', '/wishlist/remove', 'user/wishlist.php', 'remove', 'Rimuovi prodotto dalla Wishlist');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Carrello', '/checkout', 'user/cart.php', 'checkout', 'Checkout');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Ordine', '/order', 'user/cart.php', 'order', 'Completamento Ordine');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Piazzamento Ordine', '/order/place', 'user/cart.php', 'placeOrder', 'Piazzamento Ordine');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Ordine', '/method/create', 'user/profile.php', 'addPaymentMethod', 'Metodo di pagamento');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Ordine', '/address/create', 'user/profile.php', 'addShipmentAddress', 'Indirizzo di spedizione');
INSERT INTO service (tag, url, script, callback, service_description) VALUES ('Recensione', '/reviews/add', 'user/review.php', 'add', 'Aggiungi Review');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione utenti' , 'Visualizza utenti', '/admin/users', 'admin/users.php', 'users');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione gruppi', 'Visualizza gruppi', '/admin/groups', 'admin/groups.php', 'groups');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione prodotti', 'Visualizza prodotti', '/admin/products', 'admin/products.php', 'products');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione offerte', 'Visualizza offerte', '/admin/offers', 'admin/offers.php', 'offers');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione categorie', 'Visualizza singola categoria', '/admin/categories/%', 'admin/categories.php', 'category');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione categorie', 'Categorie', '/admin/categories', 'admin/categories.php', 'categories');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione categorie', 'Aggiungi categoria', '/admin/categories/create', 'admin/categories.php', 'create');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione prodotti', 'Aggiungi prodotto', '/admin/products/create', 'admin/products.php', 'create');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione categorie', 'Modifica categoria', '/admin/categories/%/edit', 'admin/categories.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione categorie', 'Cancella categoria', '/admin/categories/%/delete', 'admin/categories.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione offerte', 'Visualizza offerta', '/admin/offers/%', 'admin/offers.php', 'offer');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione offerte', 'Modifica offerta', '/admin/offers/%/edit', 'admin/offers.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione offerte', 'Cancella offerta', '/admin/offers/%/delete', 'admin/offers.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione offerte', 'Aggiungi offerta', '/admin/offers/create', 'admin/offers.php', 'create');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione brand', 'Visualizza tutti i brand', '/admin/brands', 'admin/brands.php', 'brands');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione brand', 'Modifica brand', '/admin/brands/%/edit', 'admin/brands.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione brand', 'Cancella brand', '/admin/brands/%/delete', 'admin/brands.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione brand', 'Aggiungi brand', '/admin/brands/create', 'admin/brands.php', 'create');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione brand', 'Visualizza brand', '/admin/brands/%', 'admin/brands.php', 'brand');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione coupon', 'Visualizza coupon', '/admin/coupon/%', 'admin/coupon.php', 'coupon');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione coupon', 'Visualizza tutti i coupon', '/admin/coupons', 'admin/coupons.php', 'coupons');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione coupon', 'Modifica coupon', '/admin/coupons/%/edit', 'admin/coupons.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione coupon', 'Cancella coupon', '/admin/coupons/%/delete', 'admin/coupons.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione coupon', 'Aggiungi coupon', '/admin/coupons/create', 'admin/coupons.php', 'create');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione coupon', 'Visualizza coupon', '/admin/coupons/%', 'admin/coupons.php', 'coupon');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione slider', 'Modifica slider', '/admin/slider/%/edit', 'admin/slider.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione slider', 'Visualizza slider', '/admin/slider/%', 'admin/slider.php', 'slider');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione slider', 'Cancella slider', '/admin/slider/%/delete', 'admin/slider.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione slider', 'Aggiungi slider', '/admin/slider/create', 'admin/slider.php', 'create');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione slider', 'Visualizza tutti gli slider', '/admin/slider', 'admin/slider.php', 'sliders');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione recensioni', 'Visualizza recensioni', '/admin/reviews', 'admin/reviews.php', 'reviews');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione immagini', 'Cancella immagini', '/admin/products/%/images/%/delete', 'admin/products.php', 'delete_image');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione prodotti', 'Visualizza prodotto', '/admin/products/%', 'admin/products.php', 'product');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione prodotti', 'Modifica prodotto', '/admin/products/%/edit', 'admin/products.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione prodotti', 'Cancella prodotto', '/admin/products/%/delete', 'admin/products.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione personalizzazione', 'Visualizza e modifica personalizzazioni', '/admin/customization', 'admin/customization.php', 'customization');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione gruppi', 'Aggiungi gruppo', '/admin/groups/create', 'admin/groups.php', 'create');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione gruppi', 'Modifica gruppo', '/admin/groups/%/edit', 'admin/groups.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione gruppi', 'Cancella gruppo', '/admin/groups/%/delete', 'admin/groups.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione ordini', 'Visualizza ordini', '/admin/orders', 'admin/orders.php', 'orders');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione ordini', 'Visualizza ordine', '/admin/orders/%', 'admin/orders.php', 'order');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione ordini', 'Modifica ordine', '/admin/orders/%/edit', 'admin/orders.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione utenti', 'Visualizza  utente', '/admin/users/%', 'admin/users.php', 'user');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione utenti', 'Modifica utente', '/admin/users/%/edit', 'admin/users.php', 'edit');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione utenti', 'Cancella utente', '/admin/users/%/delete', 'admin/users.php', 'delete');
INSERT INTO service (tag, service_description, url, script, callback) VALUES ('Gestione gruppi', 'Visualizza gruppo', '/admin/groups/%', 'admin/groups.php', 'group');
